// Generated by https://quicktype.io

export interface TopLevel {
  name:             string;
  displayName:      string;
  description:      string;
  version:          string;
  publisher:        string;
  repository:       Repository;
  engines:          Engines;
  categories:       string[];
  activationEvents: string[];
  main:             string;
  contributes:      Contributes;
  scripts:          Scripts;
  devDependencies:  { [key: string]: string };
}

export interface Contributes {
  commands:    Command[];
  keybindings: Keybinding[];
  menus:       Menus;
}

export interface Command {
  command:   string;
  title:     string;
  category?: string;
}

export interface Keybinding {
  command: string;
  key:     string;
  mac:     string;
  when:    string;
}

export interface Menus {
  "editor/context": EditorContext[];
}

export interface EditorContext {
  command: string;
  group:   string;
}

export interface Engines {
  vscode: string;
}

export interface Repository {
  url: string;
}

export interface Scripts {
  "vscode:prepublish": string;
  compile:             string;
  watch:               string;
  pretest:             string;
  test:                string;
}
